package assemblyai

const fakeAudioURL = "https://example.com/wildfires.mp3"
const fakeTranscriptID = "TRANSCRIPT_ID"

const (
	lemurSummaryWildfires     = "Wildfires in Canada are causing poor air quality and health issues in parts of the US. Weather systems are channeling smoke into the Mid-Atlantic and Northeast. The smoke contains high levels of particulate matter, microscopic particles that can harm health. Concentrations of particulate matter have reached up to 10 times the annual average and 4 times the 24-hour limit. Exposure can lead to respiratory, cardiovascular and neurological issues, especially in vulnerable groups like children, the elderly, and those with preexisting conditions. \n\nThe impacts will shift over the next few days as weather changes. The fires may continue for some time but the smoke should move away from the current affected areas. Climate change is projected to lead to longer fire seasons, more frequent fires, and more widespread air quality issues, though the Eastern US has been less affected historically."
	lemurActionItemsWildfires = "\n •Issue air quality alerts for areas downwind of wildfire smoke. \n•Cancel outdoor activities for vulnerable groups like children, elderly and those with respiratory issues.\n•Monitor air quality levels frequently in areas with high smoke concentrations.\n•Shift resources like firefighting equipment and personnel to areas with active wildfires.\n•Educate public on health impacts of wildfire smoke exposure and steps to minimize risk.\n•Research long-term solutions for mitigating effects of wildfire smoke as fire seasons worsen."
	lemurTaskWildfires        = "\n Overall, the interview provides a good overview of the wildfire smoke situation, explaining the causes, health impacts, and who is most at risk. However, the interview could be improved in a few ways:\n\n\"So what is it in this haze that makes it harmful? And I\u0026#39;m assuming it is is it is the levels outside right now in Baltimore are considered unhealthy.\" \nThe interviewer assumes the smoke is harmful and unhealthy, rather than asking an open-ended question. It would be better to ask \"What specifically in the wildfire smoke can be harmful to health?\"\n\n\"Yeah. So the concentration of particulate matter I was looking at some of the monitors that we have was reaching levels of what are, in science speak, 150 micrograms per meter cubed, which is more than ten times what the annual average should be, and about four times higher than what you\u0026#39;re supposed to have on a 24 hours average.\"\nThe explanation of particulate matter concentrations is confusing, mixing up annual and 24-hour standards. It would be clearer to say the levels were 10 times the annual standard and 4 times the 24-hour standard. \n\n\"I was going to ask you, more fires start burning, I don\u0026#39;t expect the concentrations to go up too much higher.\" \nThe interviewer contradicts themselves here, first saying they were going to ask about increasing fires, then saying concentrations won't go much higher. This could be clarified.\n\n\"And so I think that\u0026#39;s going to be the defining factor. And I think the next couple of days we\u0026#39;re going to see a shift in that weather pattern and start to push the smoke away from where we are.\"\nThe expert speculates that weather changes will push the smoke away in the next couple days, but this is uncertain. It would be better to indicate that weather changes could potentially push the smoke away, depending on how the weather systems shift.\n\n\"This tends to be much more of an issue in the Western US. So the Eastern US getting hit right now is a little bit new.\" \nThe statement that wildfire smoke impacts are \"new\" to the Eastern US is an overgeneralization. While less frequent, wildfire smoke from Canada and the Western US has reached the East in past years as well. It would be more accurate to say \"less common\" or \"more unusual.\""
)
